### PR TITLE
Fix Lemonloader issues

### PR DESCRIPTION
**Pull request by KitchenBoy08**
- Switched to JSON saving for DataSaver
 + Might need some form of encryption so that people can't give themselves items
- Switched patches for working ones
- Switched IL2 Arrays for System Arrays

### CODE REVIEW

**Comment by KitchenBoy08** [comment]
There are more issues I need to look into, like some random null refs that cause performance issues

**Comment by Lakatrazz** [comment]
Also changes the GUIDS of every asset in fusionbundles for some reason

**Comment by KitchenBoy08** [comment]
odd, lemme see what I can do

**Comment by KitchenBoy08** [comment]
These are the same files as are on Github
If it shows they're changed then that's cause I deleted the entire folder and just replaced it :P

**Comment by KitchenBoy08** [comment]
Time to fix conflicts ❤️

**Pull request closed without merging**
