### PR TITLE
Fix issues with Network Layer Determination

### PR DESCRIPTION
**Pull request by KitchenBoy08**

### CODE REVIEW

**Comment by KitchenBoy08** [comment]
Doing this for FNPlus cause I plan to add other network layers than Riptide :P
Might as well make alat somewhat polished

**Comment by Lakatrazz** [comment]
Why add a second function element that updates the network layer? It seems redundant

**Comment by KitchenBoy08** [comment]
Oh yeah the title wasn't updating while inside the page which is a bonelib issue and the chances of that being fixed in the foreseeable future is like none lmao

**Comment by KitchenBoy08** [comment]
That's like the only actual issue with network layer determination Ive found so far I believe but it was annoying enough

**Comment by Lakatrazz** [comment]
Should probably change the title of the page to "Change Layer" then and remove the functionality from the target layer button

**Comment by KitchenBoy08** [comment]
done

**Pull request merged**
