### PR TITLE
Implement Unity Microphone

### PR DESCRIPTION
**Pull request by KitchenBoy08**
I also refactored a couple things that are decently easy to change back, like
- Moved *most* code for getting the audio data from the player to the InternalServerHelpers.OnVoiceChatUpdate() update and added a parameter for voiceData, which is in its uncompressed form
- Added a very simple compression and decompression method to VoiceHelper
- HOPEFULLY fixed delay and audio distortion issues, just a matter of tweaking the voice detection sensitivity 🔥
- Added support for hot-swapping the microphone, but can definitely be improved (as can all of this lol, just didn't seem like anyone felt like doing this)

### CODE REVIEW

**Comment by KitchenBoy08** [comment]
Oh also I bumped the lang version because C# 9.0 is lameeee

**Comment by Lakatrazz** [comment]
May have to revert this for now, appears to cause instant crashes upon joining on quest

**Comment by Lakatrazz** [comment]
Gonna have to revert, cant get this to work

**Comment by JTMCDev** [comment]
aw boohoo :(

**Pull request merged**
