### PR TITLE
Lemonloader Fixes

### PR DESCRIPTION
**Pull request by KitchenBoy08**
Just gonna create a draft for all my changes cause Lemon seems to have a new issue every other day

### CODE REVIEW

**Comment by KitchenBoy08** [comment]
Right now just fixes a broken Jump patch and slightly moves the Vision Obstructer forward since occasionally it would clip into the camera.

**Comment by Lakatrazz** [comment]
I remember patching the RemapRig jump methods causing crashes on PC, also it modified all the fusion bundle assets agaaain

**Comment by KitchenBoy08** [comment]
I think it's modifying the bundles cause Im packing for quest, not entirely sure what to do other than replace the folder every time I pack

**Comment by KitchenBoy08** [comment]
And if that remap rig thing is true then crap

**Pull request closed without merging**
