### PR TITLE
Patch 4 fixes

### PR DESCRIPTION
**Pull request by KitchenBoy08**

### CODE REVIEW

**Comment by KitchenBoy08** [comment]
Had to open a new PR cause I renamed the branch :P

**Comment by KitchenBoy08** [comment]
Alright, I think this is ready to merge

**Comment by KitchenBoy08** [comment]
Just discovered issue  with reading data, don't merge 0.0

**Comment by KitchenBoy08** [comment]
Alright, fixed

**Comment by KitchenBoy08** [comment]
Alright this is probably good, but just so you know Quest performance is awfully poor for no particularly clear reason :P

**Comment by Lakatrazz** [comment]
Am a little confused why LabFusionUpdater was modified since it doesn't work on quest in the first place, but looks good. There are a few added null checks I'm going to remove since they should never be null anyways unless something is seriously wrong with the game or mod, in which they should probably be throwing an error anyways

**Comment by KitchenBoy08** [comment]
Likely just me debugging and forgetting to remove it lol

**Comment by KitchenBoy08** [comment]
Oh and the reason the Updater was updated was cause I believe it needs to be updated to Net 6 for it to work on Melon 0.6, I just did that so it would compile properly

**Pull request merged**
