### PR TITLE
Draft: Refactor project structure, code cleanup

### PR DESCRIPTION
**Pull request by Meister1593**
Reorganize solution structure to have 1 project = 1 folder
Reformat, cleanup unnecessary code (unnecessary default values assignments, imports optimize)

Currently in draft as i'm still checking what to do and most importantly - while it compiles on my end on Linux under mono with msbuild 15, i haven't tried compiling this pr on windows (i'm going to do it on vm), and i haven't tested fully compiled dll with other players.
Would also need users on windows, linux, mac with fusion helpers to check.
Will also try to do github actions for project (would definitely require some tinkering and custom pipelines)

### CODE REVIEW

**Comment by TrevTV** [comment]
Most of these changes feel super unnecessary and feels like you just going through and letting the IDE auto-cleanup things it doesn't like. You also moved some things to NuGet packages without any additional work. They were embedded into the project to allow it to be all in a single DLL and not dealing with janky merging or unexpected version changes, as well as just making it much easier for a user to install it. You also seemingly removed the Steam API libraries from FusionHelper, those are required for it to function, not sure why you thought that was a good idea. Also, it's generally not a good idea to make such a large PR without discussing it with the primary developer, it's usually better to keep new PRs to fixing (smaller) things, rather than giant changes with no impact on functionality.

**Comment by Meister1593** [comment]
> Most of these changes feel super unnecessary and feels like you just going through and letting the IDE auto-cleanup things it doesn't like. You also moved some things to NuGet packages without any additional work. They were embedded into the project to allow it to be all in a single DLL and not dealing with janky merging or unexpected version changes, as well as just making it much easier for a user to install it. You also seemingly removed the Steam API libraries from FusionHelper, those are required for it to function, not sure why you thought that was a good idea. Also, it's generally not a good idea to make such a large PR without discussing it with the primary developer, it's usually better to keep new PRs to fixing (smaller) things, rather than giant changes with no impact on functionality.

I consulted with main dev and everything in this pr was the main intention - project cleanup, restructure. I don't deny autoformat or anything, that's the goal, just to make it a bit more appealing

I did not test it fully yet, thus why its a draft. I wasn't intending to leave it as is without any additional testing.

**Comment by TrevTV** [comment]
I was thinking more properly working with the dev instead of just asking if you could, I understand this is a draft, but there are a lot of would-be obvious things you missed, but probably wouldn't have if you had discussed it more with him.

**Comment by Meister1593** [comment]
This is still highly WIP pr, and I intended to fully test it in any case. Nothing is gonna be even remotely close to be merged until it gets properly tested.

**Comment by Meister1593** [comment]
Decided against of moving to nuget or submodules, they already kind of got changed and tailored for single bundle and other means of bundling inside of one dll wouldn't do much good or just way too complicated.
Will proceed with other code checkup/cleanup

**Comment by Meister1593** [comment]
Will close it since melon loader 0.6 update anyway gonna change project significantly, and this will no longer be relevant

**Pull request closed without merging**
