### PR TITLE
Convert self supplied Assemblies to BONELAB_DIR Enviroment Variable

### PR DESCRIPTION
**Pull request by Lightmaxifrvr**
Generally Makes it easier/faster to compile/make pull requests to.

### CODE REVIEW

**Comment by JTMCDev** [comment]
Honestly I don't see how anyone is going to use this other than developers making custom game modes maybe? I guess its QOL so, worth it?

**Comment by Checkerb0ard** [comment]
the current way of creating a managed folder works fine imo

**Comment by capybarajtmc** [comment]
I was hating on this. But its actually really useful

**Comment by Lightmaxifrvr** [comment]
ill update it to fix the merge problem

**Comment by Lakatrazz** [comment]
Added in c23e1b07a9e617fa19881dbbb7c55ef47fa86065 now

**Pull request closed without merging**
